In [15]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 6000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [16]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np

In [17]:
model=load_model("model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [ ]:
## load our sources.
import pickle

with open("label_encoder_gender.pkl","rb") as file:
    label_encoder_gender=pickle.load(file)
with open("onehot_encoder_geo.pkl","rb") as file:
    onehot_encoder_geo=pickle.load(file)
with open("Scaler.pkl","rb") as file:
    Scaler=pickle.load(file)

In [ ]:
## One-hot_encoded
geo=onehot_encoder_geo.transform([[input_data["Geography"]]])
geo_df=pd.DataFrame(geo.toarray(),columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))
geo_df

e:\Works\NLP\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [20]:
input_data=pd.DataFrame([input_data])
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,6000,2,1,1,50000

In [21]:
#Label encoder
input_data["Gender"]=label_encoder_gender.transform([input_data["Gender"]])
input_data

e:\Works\NLP\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,6000,2,1,1,50000

In [22]:
data=pd.concat([input_data.drop(columns=["Geography"]),geo_df],axis=1)
data.head(8)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,6000,2,1,1,50000,1.0,0.0,0.0

In [23]:
data_scaler=Scaler.transform(data)

In [24]:
prediction=model.predict(data_scaler)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

In [25]:
prediction_proba=prediction[0][0]
prediction_proba

0.1834751

In [26]:
if prediction_proba > 0.5:
    print("He would like to be here")
else:
    print("He wouldnt")

He wouldnt